spring:
  security:
    basic:
      enabled: true
    user:
      name: ensk
      password: 123456
server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://ensk:123456@localhost:8761/eureka

