server:
  port: 8001
spring:
  application:
    name: spring-cloud-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://ensk:123456@localhost:8761/eureka
logging:
  level:
    root: INFO
